import { Product } from './product.entity';

export const PRODUCT_SEED: Product[] = [
  {
    id: 'p-coffee-beans',
    name: 'Single-Origin Coffee Beans 250g',
    description: 'Ethiopian Yirgacheffe — light roast, floral, citrus notes.',
    category: 'pantry',
    priceCents: 1299,
    stock: 24,
    imageUrl: 'https://images.example.com/coffee.jpg',
  },
  {
    id: 'p-oat-milk',
    name: 'Barista Oat Milk 1L',
    description: 'Creamy oat milk, steams beautifully.',
    category: 'dairy-alt',
    priceCents: 249,
    stock: 60,
    imageUrl: 'https://images.example.com/oat-milk.jpg',
  },
  {
    id: 'p-sourdough',
    name: 'Sourdough Loaf',
    description: 'Hand-shaped sourdough, baked fresh daily.',
    category: 'bakery',
    priceCents: 549,
    stock: 12,
    imageUrl: 'https://images.example.com/sourdough.jpg',
  },
  {
    id: 'p-dark-chocolate',
    name: 'Dark Chocolate 70% 100g',
    description: 'Single-estate dark chocolate, bittersweet finish.',
    category: 'snacks',
    priceCents: 399,
    stock: 40,
    imageUrl: 'https://images.example.com/chocolate.jpg',
  },
  {
    id: 'p-olive-oil',
    name: 'Extra Virgin Olive Oil 500ml',
    description: 'Cold-pressed Tuscan olive oil, peppery and grassy.',
    category: 'pantry',
    priceCents: 1499,
    stock: 18,
    imageUrl: 'https://images.example.com/olive-oil.jpg',
  },
  {
    id: 'p-pasta',
    name: 'Bronze-Cut Spaghetti 500g',
    description: 'Rough-textured artisan pasta, holds sauce well.',
    category: 'pantry',
    priceCents: 329,
    stock: 50,
    imageUrl: 'https://images.example.com/pasta.jpg',
  },
  {
    id: 'p-tomato-sauce',
    name: 'San Marzano Tomato Sauce 400g',
    description: 'Slow-simmered tomatoes with basil and garlic.',
    category: 'pantry',
    priceCents: 449,
    stock: 0,
    imageUrl: 'https://images.example.com/tomato.jpg',
  },
];
